/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CanvasElement: typeof import('./src/components/CanvasElement.vue')['default']
    CanvasToolBar: typeof import('./src/components/CanvasToolBar.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ContextMenuCanvas: typeof import('./src/components/ContextMenuCanvas.vue')['default']
    ContextMenuFileTree: typeof import('./src/components/ContextMenuFileTree.vue')['default']
    FileTree: typeof import('./src/components/FileTree.vue')['default']
    FloatingToolbar: typeof import('./src/components/FloatingToolbar.vue')['default']
    IconPickerModal: typeof import('./src/components/IconPickerModal.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    RichTextEditor: typeof import('./src/components/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarCog: typeof import('./src/components/SidebarCog.vue')['default']
    SidebarTrash: typeof import('./src/components/SidebarTrash.vue')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    TagModal: typeof import('./src/components/TagModal.vue')['default']
    TextEditToolbar: typeof import('./src/components/TextEditToolbar.vue')['default']
    Tree: typeof import('primevue/tree')['default']
  }
}
